image: docker:stable

stages:
- deploy
services:
  - docker:dind
variables:
  image: ${CI_PROJECT_NAME}
  DOCKER_DRIVER: overlay2
swms_deploy:
  stage: deploy
  script:
  - docker ps
  - docker build . -t $image  
  - docker push $image
